require: rubocop-rspec

AllCops:
  Exclude:
    - bin/*
    - 'db/**/*'
    - 'Guardfile'

Documentation:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

NumericLiterals:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

BlockComments:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Rails/Date:
  Enabled: false
